version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/services
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=form_templates_db

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
